# Generated by Django 4.1.4 on 2023-04-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
